### ISSUE TITLE
Mesh chooser improvements

### ISSUE THREAD

**Issue by okdistribute** [getditto/demoapp-chat#123]
Update to 4.7.2 and use `ALTER SYSTEM` to set `mesh_chooser_avoid_redundant_bluetooth` to `false` for this app

```swift
Task { [weak self] in
    do {
        try await ditto.store.execute("ALTER SYSTEM SET mesh_chooser_avoid_redundant_bluetooth = false")
    }
}
```

As discussed in [Slack](https://dittolive.slack.com/archives/C010MNVAY7N/p1718113885182009)

**Comment by kndoshn** [comment]
Closed by #95 (haven't published to app stores yet)
