### ISSUE TITLE
Update to Ditto 4.2.3

### ISSUE THREAD

**Issue by okdistribute** [getditto/demoapp-chat#63]
Latest ditto version.

**Comment by okdistribute** [comment]
We will want to update to 4.2.2, this will be out next week and worth waiting the few days

**Comment by okdistribute** [comment]
Skipping to 4.2.3

**Comment by kndoshn** [comment]
Chat apps are published based on 4.2.2.
They are using OfflinePlayground now, so they're not affected by the OnlinePlayground issue fixed in 4.2.3.
