### ISSUE TITLE
Consistent environment variable names

### ISSUE THREAD

**Issue by texasRanger09** [getditto/demoapp-chat#82]
The environment variable names differer between iOS and Android. 
Current names used:
iOS 
```
DITTO_APP_ID=
DITTO_PLAYGROUND_TOKEN=
DITTO_AUTH_PASSWORD=
DITTO_AUTH_PROVIDER=
DITTO_OFFLINE_TOKEN=
```
Android
```
DITTO_APP_ID = 
DITTO_LICENSE_TOKEN = 
DITTO_AUTH_TOKEN=
DITTO_AUTH_PROVIDER = 
```

*Update Android variables to match the iOS naming convention

**Comment by anyercastillo** [comment]
Do you think that makes sense for Android to have only one credential file instead of two?

Currently we have:
- debug_creds.properties
- release_creds.properties

Maybe a single `creds.properties` file with the suggested env vars will do the work.
```
DITTO_APP_ID=
DITTO_PLAYGROUND_TOKEN=
DITTO_AUTH_PASSWORD=
DITTO_AUTH_PROVIDER=
DITTO_OFFLINE_TOKEN=
```

**Comment by texasRanger09** [comment]
Yeah, we can use a single creds.properties file.
