### ISSUE TITLE
Enable Small Peer Info

### ISSUE THREAD

**Issue by kndoshn** [getditto/demoapp-chat#87]

**Comment by kndoshn** [comment]
To sync small peer info to Big Peer, Chat needs to
- Switch the Ditto identity to either onlinePlayground or onlineWithAuthentication to enable the cloud sync
  - This will cause an incompatibility (breaking change) because the current OfflineOnly identity isn't able to sync with the other types
- We are currently not ready to enable the cloud sync because of the app features:
  - The public room is shared by anyone who is in sync, so if we enable the cloud sync, anyone can join the same room (not desirable)
  - We need to come up with some better ways to handle public rooms or need to remove them before enabling the cloud sync

**Comment by bplattenburg** [comment]
@kndoshn Is this still something we're pursuing? Sdk 4.8.0 and newer would enable Small Peer Info by default given the appropriate identity.

**Comment by bplattenburg** [comment]
So essentially https://github.com/getditto/demoapp-chat/issues/33 would cover this as well?

**Comment by kndoshn** [comment]
We can cover with #33.
