### ISSUE TITLE
Core: Notifications/Unread for Ditto Chat

### ISSUE THREAD

**Issue by ErikEverson** [getditto/demoapp-chat#98]
- Add chat notifications and or unread UI elements.
- Update library 
- Get chat to use library instead of built in code.

Arch reference: https://lucid.app/lucidchart/b1169e2c-32a9-4821-ae2e-c555586aaa20/edit?viewport_loc=-41%2C-8%2C2841%2C3160%2C0_0&invitationId=inv_07e76850-c1a5-49f1-9e1d-31dccf8c92cc

**Comment by ErikEverson** [comment]
Updated Architecture based on feedback from @anyercastillo. 
Going to get feedback from another developer on it as well. 
I need to think through two disconnected chats in one room and how that would look or how that would be as chats could become unrelated.

**Comment by bplattenburg** [comment]
Closing this as it is marked `Done` in the linked project.

@ErikEverson or @anyercastillo please re-open if this is not actually done.
